export const COUNTRIES = [
  { en: "Afghanistan", ar: "أفغانستان", flag: "🇦🇫" },
  { en: "Albania", ar: "ألبانيا", flag: "🇦🇱" },
  { en: "Algeria", ar: "الجزائر", flag: "🇩🇿" },
  { en: "Andorra", ar: "أندورا", flag: "🇦🇩" },
  { en: "Angola", ar: "أنغولا", flag: "🇦🇴" },
  { en: "Antigua and Barbuda", ar: "أنتيغوا وباربودا", flag: "🇦🇬" },
  { en: "Argentina", ar: "الأرجنتين", flag: "🇦🇷" },
  { en: "Armenia", ar: "أرمينيا", flag: "🇦🇲" },
  { en: "Australia", ar: "أستراليا", flag: "🇦🇺" },
  { en: "Austria", ar: "النمسا", flag: "🇦🇹" },
  { en: "Azerbaijan", ar: "أذربيجان", flag: "🇦🇿" },
  { en: "Bahamas", ar: "الباهاماس", flag: "🇧🇸" },
  { en: "Bahrain", ar: "البحرين", flag: "🇧🇭" },
  { en: "Bangladesh", ar: "بنغلاديش", flag: "🇧🇩" },
  { en: "Barbados", ar: "باربادوس", flag: "🇧🇧" },
  { en: "Belarus", ar: "بيلاروس", flag: "🇧🇾" },
  { en: "Belgium", ar: "بلجيكا", flag: "🇧🇪" },
  { en: "Belize", ar: "بليز", flag: "🇧🇿" },
  { en: "Benin", ar: "بنين", flag: "🇧🇯" },
  { en: "Bhutan", ar: "بوتان", flag: "🇧🇹" },
  { en: "Bolivia", ar: "بوليفيا", flag: "🇧🇴" },
  { en: "Bosnia and Herzegovina", ar: "البوسنة والهرسك", flag: "🇧🇦" },
  { en: "Botswana", ar: "بوتسوانا", flag: "🇧🇼" },
  { en: "Brazil", ar: "البرازيل", flag: "🇧🇷" },
  { en: "Brunei", ar: "بروناي", flag: "🇧🇳" },
  { en: "Bulgaria", ar: "بلغاريا", flag: "🇧🇬" },
  { en: "Burkina Faso", ar: "بوركينا فاسو", flag: "🇧🇫" },
  { en: "Burundi", ar: "بوروندي", flag: "🇧🇮" },
  { en: "Cambodia", ar: "كمبوديا", flag: "🇰🇭" },
  { en: "Cameroon", ar: "الكاميرون", flag: "🇨🇲" },
  { en: "Canada", ar: "كندا", flag: "🇨🇦" },
  { en: "Cape Verde", ar: "الرأس الأخضر", flag: "🇨🇻" },
  { en: "Central African", ar: "أفريقيا الوسطى", flag: "🇨🇫" },
  { en: "Chad", ar: "تشاد", flag: "🇹🇩" },
  { en: "Chile", ar: "تشيلي", flag: "🇨🇱" },
  { en: "China", ar: "الصين", flag: "🇨🇳" },
  { en: "Colombia", ar: "كولومبيا", flag: "🇨🇴" },
  { en: "Comoros", ar: "جزر القمر", flag: "🇰🇲" },
  { en: "Congo", ar: "الكونغو", flag: "🇨🇬" },
  { en: "Costa Rica", ar: "كوستاريكا", flag: "🇨🇷" },
  { en: "Croatia", ar: "كرواتيا", flag: "🇭🇷" },
  { en: "Cuba", ar: "كوبا", flag: "🇨🇺" },
  { en: "Cyprus", ar: "قبرص", flag: "🇨🇾" },
  { en: "Czechia", ar: "التشيك", flag: "🇨🇿" },
  { en: "Denmark", ar: "الدنمارك", flag: "🇩🇰" },
  { en: "Djibouti", ar: "جيبوتي", flag: "🇩🇯" },
  { en: "Dominica", ar: "دومينيكا", flag: "🇩🇲" },
  { en: "Dominican", ar: "الدومينيك", flag: "🇩🇴" },
  { en: "DR Congo", ar: "الكونغو الديمقراطية", flag: "🇨🇩" },
  { en: "Ecuador", ar: "الإكوادور", flag: "🇪🇨" },
  { en: "Egypt", ar: "مصر", flag: "🇪🇬" },
  { en: "El Salvador", ar: "السلفادور", flag: "🇸🇻" },
  { en: "Equatorial Guinea", ar: "غينيا الاستوائية", flag: "🇬🇶" },
  { en: "Eritrea", ar: "إريتريا", flag: "🇪🇷" },
  { en: "Estonia", ar: "إستونيا", flag: "🇪🇪" },
  { en: "Eswatini", ar: "إسواتيني", flag: "🇸🇿" },
  { en: "Ethiopia", ar: "إثيوبيا", flag: "🇪🇹" },
  { en: "Fiji", ar: "فيجي", flag: "🇫🇯" },
  { en: "Finland", ar: "فنلندا", flag: "🇫🇮" },
  { en: "France", ar: "فرنسا", flag: "🇫🇷" },
  { en: "Gabon", ar: "الغابون", flag: "🇬🇦" },
  { en: "Gambia", ar: "غامبيا", flag: "🇬🇲" },
  { en: "Georgia", ar: "جورجيا", flag: "🇬🇪" },
  { en: "Germany", ar: "ألمانيا", flag: "🇩🇪" },
  { en: "Ghana", ar: "غانا", flag: "🇬🇭" },
  { en: "Greece", ar: "اليونان", flag: "🇬🇷" },
  { en: "Grenada", ar: "غرينادا", flag: "🇬🇩" },
  { en: "Guatemala", ar: "غواتيمالا", flag: "🇬🇹" },
  { en: "Guinea", ar: "غينيا", flag: "🇬🇳" },
  { en: "Guinea-Bissau", ar: "غينيا بيساو", flag: "🇬🇼" },
  { en: "Guyana", ar: "غيانا", flag: "🇬🇾" },
  { en: "Haiti", ar: "هايتي", flag: "🇭🇹" },
  { en: "Honduras", ar: "هندوراس", flag: "🇭🇳" },
  { en: "Hungary", ar: "المجر", flag: "🇭🇺" },
  { en: "Iceland", ar: "آيسلندا", flag: "🇮🇸" },
  { en: "India", ar: "الهند", flag: "🇮🇳" },
  { en: "Indonesia", ar: "إندونيسيا", flag: "🇮🇩" },
  { en: "Iran", ar: "إيران", flag: "🇮🇷" },
  { en: "Iraq", ar: "العراق", flag: "🇮🇶" },
  { en: "Ireland", ar: "أيرلندا", flag: "🇮🇪" },
  { en: "Israel", ar: "إسرائيل", flag: "🇮🇱" },
  { en: "Italy", ar: "إيطاليا", flag: "🇮🇹" },
  { en: "Jamaica", ar: "جامايكا", flag: "🇯🇲" },
  { en: "Japan", ar: "اليابان", flag: "🇯🇵" },
  { en: "Jordan", ar: "الأردن", flag: "🇯🇴" },
  { en: "Kazakhstan", ar: "كازاخستان", flag: "🇰🇿" },
  { en: "Kenya", ar: "كينيا", flag: "🇰🇪" },
  { en: "Kiribati", ar: "كيريباتي", flag: "🇰🇮" },
  { en: "Kuwait", ar: "الكويت", flag: "🇰🇼" },
  { en: "Kyrgyzstan", ar: "قيرغيزستان", flag: "🇰🇬" },
  { en: "Laos", ar: "لاوس", flag: "🇱🇦" },
  { en: "Latvia", ar: "لاتفيا", flag: "🇱🇻" },
  { en: "Lebanon", ar: "لبنان", flag: "🇱🇧" },
  { en: "Lesotho", ar: "ليسوتو", flag: "🇱🇸" },
  { en: "Liberia", ar: "ليبيريا", flag: "🇱🇷" },
  { en: "Libya", ar: "ليبيا", flag: "🇱🇾" },
  { en: "Liechtenstein", ar: "ليختنشتاين", flag: "🇱🇮" },
  { en: "Lithuania", ar: "ليتوانيا", flag: "🇱🇹" },
  { en: "Luxembourg", ar: "لوكسمبورغ", flag: "🇱🇺" },
  { en: "Madagascar", ar: "مدغشقر", flag: "🇲🇬" },
  { en: "Malawi", ar: "مالاوي", flag: "🇲🇼" },
  { en: "Malaysia", ar: "ماليزيا", flag: "🇲🇾" },
  { en: "Maldives", ar: "المالديف", flag: "🇲🇻" },
  { en: "Mali", ar: "مالي", flag: "🇲🇱" },
  { en: "Malta", ar: "مالطا", flag: "🇲🇹" },
  { en: "Marshall Islands", ar: "جزر مارشال", flag: "🇲🇭" },
  { en: "Mauritania", ar: "موريتانيا", flag: "🇲🇷" },
  { en: "Mauritius", ar: "موريشيوس", flag: "🇲🇺" },
  { en: "Mexico", ar: "المكسيك", flag: "🇲🇽" },
  { en: "Micronesia", ar: "ميكرونيزيا", flag: "🇫🇲" },
  { en: "Moldova", ar: "مولدوفا", flag: "🇲🇩" },
  { en: "Monaco", ar: "موناكو", flag: "🇲🇨" },
  { en: "Mongolia", ar: "منغوليا", flag: "🇲🇳" },
  { en: "Montenegro", ar: "الجبل الأسود", flag: "🇲🇪" },
  { en: "Morocco", ar: "المغرب", flag: "🇲🇦" },
  { en: "Mozambique", ar: "موزمبيق", flag: "🇲🇿" },
  { en: "Myanmar", ar: "ميانمار", flag: "🇲🇲" },
  { en: "Namibia", ar: "ناميبيا", flag: "🇳🇦" },
  { en: "Nauru", ar: "ناورو", flag: "🇳🇷" },
  { en: "Nepal", ar: "نيبال", flag: "🇳🇵" },
  { en: "Netherlands", ar: "هولندا", flag: "🇳🇱" },
  { en: "New Zealand", ar: "نيوزيلندا", flag: "🇳🇿" },
  { en: "Nicaragua", ar: "نيكاراغوا", flag: "🇳🇮" },
  { en: "Niger", ar: "النيجر", flag: "🇳🇪" },
  { en: "Nigeria", ar: "نيجيريا", flag: "🇳🇬" },
  { en: "North Korea", ar: "كوريا الشمالية", flag: "🇰🇵" },
  { en: "North Macedonia", ar: "مقدونيا الشمالية", flag: "🇲🇰" },
  { en: "Norway", ar: "النرويج", flag: "🇳🇴" },
  { en: "Oman", ar: "عمان", flag: "🇴🇲" },
  { en: "Pakistan", ar: "باكستان", flag: "🇵🇰" },
  { en: "Palau", ar: "بالاو", flag: "🇵🇼" },
  { en: "Palestine", ar: "فلسطين", flag: "🇵🇸" },
  { en: "Panama", ar: "بنما", flag: "🇵🇦" },
  { en: "Papua New Guinea", ar: "بابوا غينيا الجديدة", flag: "🇵🇬" },
  { en: "Paraguay", ar: "باراغواي", flag: "🇵🇾" },
  { en: "Peru", ar: "بيرو", flag: "🇵🇪" },
  { en: "Philippines", ar: "الفلبين", flag: "🇵🇭" },
  { en: "Poland", ar: "بولندا", flag: "🇵🇱" },
  { en: "Portugal", ar: "البرتغال", flag: "🇵🇹" },
  { en: "Qatar", ar: "قطر", flag: "🇶🇦" },
  { en: "Romania", ar: "رومانيا", flag: "🇷🇴" },
  { en: "Russia", ar: "روسيا", flag: "🇷🇺" },
  { en: "Rwanda", ar: "رواندا", flag: "🇷🇼" },
  { en: "Saint Kitts and Nevis", ar: "سانت كيتس ونيفيس", flag: "🇰🇳" },
  { en: "Saint Lucia", ar: "سانت لوسيا", flag: "🇱🇨" },
  {
    en: "Saint Vincent and Grenadines",
    ar: "سانت فنسنت والغرينادين",
    flag: "🇻🇨",
  },
  { en: "Samoa", ar: "ساموا", flag: "🇼🇸" },
  { en: "San Marino", ar: "سان مارينو", flag: "🇸🇲" },
  { en: "Sao Tome and Principe", ar: "ساو تومي وبرينسيب", flag: "🇸🇹" },
  { en: "Saudi Arabia", ar: "السعودية", flag: "🇸🇦" },
  { en: "Senegal", ar: "السنغال", flag: "🇸🇳" },
  { en: "Serbia", ar: "صربيا", flag: "🇷🇸" },
  { en: "Seychelles", ar: "سيشيل", flag: "🇸🇨" },
  { en: "Sierra Leone", ar: "سيراليون", flag: "🇸🇱" },
  { en: "Singapore", ar: "سنغافورة", flag: "🇸🇬" },
  { en: "Slovakia", ar: "سلوفاكيا", flag: "🇸🇰" },
  { en: "Slovenia", ar: "سلوفينيا", flag: "🇸🇮" },
  { en: "Solomon Islands", ar: "جزر سليمان", flag: "🇸🇧" },
  { en: "Somalia", ar: "الصومال", flag: "🇸🇴" },
  { en: "South Africa", ar: "جنوب أفريقيا", flag: "🇿🇦" },
  { en: "South Korea", ar: "كوريا الجنوبية", flag: "🇰🇷" },
  { en: "South Sudan", ar: "جنوب السودان", flag: "🇸🇸" },
  { en: "Spain", ar: "إسبانيا", flag: "🇪🇸" },
  { en: "Sri Lanka", ar: "سريلانكا", flag: "🇱🇰" },
  { en: "Sudan", ar: "السودان", flag: "🇸🇩" },
  { en: "Suriname", ar: "سورينام", flag: "🇸🇷" },
  { en: "Sweden", ar: "السويد", flag: "🇸🇪" },
  { en: "Switzerland", ar: "سويسرا", flag: "🇨🇭" },
  { en: "Syria", ar: "سوريا", flag: "🇸🇾" },
  { en: "Taiwan", ar: "تايوان", flag: "🇹🇼" },
  { en: "Tajikistan", ar: "طاجيكستان", flag: "🇹🇯" },
  { en: "Tanzania", ar: "تنزانيا", flag: "🇹🇿" },
  { en: "Thailand", ar: "تايلاند", flag: "🇹🇭" },
  { en: "Timor-Leste", ar: "تيمور الشرقية", flag: "🇹🇱" },
  { en: "Togo", ar: "توغو", flag: "🇹🇬" },
  { en: "Tonga", ar: "تونغا", flag: "🇹🇴" },
  { en: "Trinidad and Tobago", ar: "ترينيداد وتوباغو", flag: "🇹🇹" },
  { en: "Tunisia", ar: "تونس", flag: "🇹🇳" },
  { en: "Turkey", ar: "تركيا", flag: "🇹🇷" },
  { en: "Turkmenistan", ar: "تركمانستان", flag: "🇹🇲" },
  { en: "Tuvalu", ar: "توفالو", flag: "🇹🇻" },
  { en: "Uganda", ar: "أوغندا", flag: "🇺🇬" },
  { en: "Ukraine", ar: "أوكرانيا", flag: "🇺🇦" },
  { en: "United Arab Emirates", ar: "الإمارات", flag: "🇦🇪" },
  { en: "United Kingdom", ar: "المملكة المتحدة", flag: "🇬🇧" },
  { en: "United States", ar: "الولايات المتحدة", flag: "🇺🇸" },
  { en: "Uruguay", ar: "أوروغواي", flag: "🇺🇾" },
  { en: "Uzbekistan", ar: "أوزبكستان", flag: "🇺🇿" },
  { en: "Vanuatu", ar: "فانواتو", flag: "🇻🇺" },
  { en: "Venezuela", ar: "فنزويلا", flag: "🇻🇪" },
  { en: "Vietnam", ar: "فيتنام", flag: "🇻🇳" },
  { en: "Yemen", ar: "اليمن", flag: "🇾🇪" },
  { en: "Zambia", ar: "زامبيا", flag: "🇿🇲" },
  { en: "Zimbabwe", ar: "زيمبابوي", flag: "🇿🇼" },
];
